packages:
  - "facilitator"
  - "servers/*"
  - "clients/*"
  - "fullstack/*"
  - "dynamic_agent"
  - "agent"
  - "mcp-embedded-wallet"
  - "mpc"
  - "discovery"
  - "../aptos/typescript/*/client"
  - "../aptos/typescript/*/server"
  - "../../typescript/packages/*"
